import os

os.makedirs("python", exist_ok=True)

lines = [
    "# Python 변수 및 자료형 (Variables & Data Types)",
    "",
    "## 1. 개요 및 기본 문법",
    "",
    "### 주석 (Comments)",
    "- 단일 라인 주석: `#` 사용",
    "- 여러 줄 주석 (Docstring): 따옴표 3개 사용",
    "",
    "### 출력문 (print)",
    "- 콘솔 출력 함수: `print('출력 내용')`",
    "",
    "### 변수 (Variables)",
    "- 값을 저장하는 메모리 공간의 식별자",
    "- 파이썬은 **동적 타입 언어**로 런타임에 값에 따라 타입이 자동 추론됩니다.",
    "",
    "| 구분 | 정적 타입 언어 (Static Type) | 동적 타입 언어 (Dynamic Type) |",
    "| :--- | :--- | :--- |",
    "| 타입 결정 시점 | 컴파일 타임 (타입 지정 필수) | 런타임 (값 할당 시 자동 추론) |",
    "| 대표 언어 | Java, C, C++, Rust | Python, JavaScript |",
    "",
    "---",
    "",
    "## 2. 기본 자료형 (Scalar Types)",
    "",
    "| 자료형 | 식별자 | 예시 | 설명 |",
    "| :--- | :--- | :--- | :--- |",
    "| 정수형 | `int` | `10`, `-5`, `0` | 8진수(`0o34`), 16진수(`0x2A`) 지원 |",
    "| 실수형 | `float` | `3.14`, `-1234.5` | 부동소수점 표현 지원 |",
    "| 문자열 | `str` | `'hello'` | 순서 있음, 수정 불가 (Immutable) |",
    "| 불리언 | `bool` | `True`, `False` | 논리 참/거짓 |",
    "| 널 타입 | `NoneType` | `None` | 값이 존재하지 않음을 명시 |",
    "",
    "### 문자열(str) 인덱싱",
    "- 문자열은 `0`번부터 시작하는 인덱스를 가집니다.",
    "- 내부 요소를 직접 수정할 수 없는 불변(Immutable) 객체입니다.",
    "",
    "---",
    "",
    "## 3. 복합 자료형 (Collections)",
    "",
    "| 자료형 | 생성 문법 | 순서(Index) | 수정 가능 여부 | 중복 허용 |",
    "| :--- | :--- | :--- | :--- | :--- |",
    "| List | `[1, 2, 3]` | 지원 | 수정 가능 (Mutable) | 허용 |",
    "| Tuple | `(1, 2, 3)` | 지원 | 수정 불가 (Immutable) | 허용 |",
    "| Dict | `{'key': 'val'}` | 키 기반 매핑 | 수정 가능 | Key 중복 불가 |",
    "| Set | `{1, 2, 3}` | 미지원 | 수정 가능 | 자동 중복 제거 |",
    "",
    "### List 주요 메서드",
    "- `.append(x)`: 리스트 끝에 요소 추가",
    "- `.insert(i, x)`: 지정 인덱스 위치에 요소 삽입",
    "- `.remove(x)`: 지정한 첫 번째 값 삭제",
    "- `.pop()`: 마지막 요소를 꺼내며 삭제",
    "- `.sort()`: 오름차순 정렬",
    "",
    "### Tuple 특징",
    "- 단일 요소 선언 시 쉼표 필수: `(1,)`",
    "- List 대비 메모리 소모가 적고 속도가 빠름",
    "",
    "### Dictionary 주요 메서드",
    "- `.get(key)`: 키로 값 조회 (부재 시 None 반환)",
    "- `.keys()`: 전체 Key 목록 반환",
    "- `.values()`: 전체 Value 목록 반환",
    "- `.items()`: (Key, Value) 쌍 목록 반환",
    "- `.clear()`: 전체 요소 삭제",
    "",
    "### Set 주요 메서드",
    "- `.add(x)`: 요소 추가",
    "- `.discard(x)`: 요소 삭제 (값 없어도 통과)",
    "- `.remove(x)`: 요소 삭제 (값 없으면 에러)",
    "",
    "---",
    "",
    "## 4. 참고 레퍼런스",
    "- 점프 투 파이썬: https://wikidocs.net/book/1",
    "- 프로그래머스 코딩테스트: https://school.programmers.co.kr/learn/challenges?order=recent",
]

with open("python/01-variables-and-data-types.md", "w", encoding="utf-8") as f:
    f.write("\n".join(lines) + "\n")

print("Complete")